- index.html
The underlying library accepts a wide range of filetypes, no need to restrict it to just png. I wanted to use a jpg.
> Allow other image file types

- scripts/on_env_start.sh
- scripts/on_sd_start.sh
- scripts/post_activate.sh
- scripts/start.sh
Add `#!/bin/bash` to all `.sh` files.
This is generally always a good idea, as it forces the sh files to run in a specific shell (in this case bash), which prevents the scripts crashing out when someone runs it from a different shell.
> Add shebangs to all sh files

- ui/index.html
This change ensures that the minus sign doesn't change size for the tiny cards, after the user has changed the card sizes. Nothing major, but will be more pleasing to look at.
> Minor css change for the tiny modifier cards

- ui/media/main.js
Disable 'resizeInpaintingEditor' when 'maskSetting' is unchecked and run 'resizeInpaintingEditor' once when 'maskSetting' is changed in case the aspect ratio was changed while 'resizeInpaintingEditor' was hidden.
> Resize in-painting disable

- ui/media/main.js
I was originally writing a bug report, but felt this was more helpful.
Downloading an image sets the filename to [prompt]_Seed-[seed]_Steps-[steps]....etc
The [prompt] section is always whatever the last prompt was instead of the prompt associated with that image generation.
My changes embed the prompt, inference steps, and guidance scale into the imageData object, to be used when generating the file name.
To reproduce the issue this fixes:
Start generating one image, say "Male portrait, Figurative"
Enqueue a second, say "Male portrait, Constructivist"
Click "Download" on the first image
the file name will be  "male_portrait__constructivist", the correct seed, but the steps/guidance will be whatever was last used, not what was used for that image
> Downloaded images named with their correct prompt and settings

- ui/sd_internal/runtime.py
- ui/server.py
Fix for https://github.com/cmdr2/stable-diffusion-ui/issues/332
Force open to use encoding utf-8 for text file operations. Fixes systems where the default is another encoding.
> Force encoding to utf-8 on text file operations Fixes #332

- ui/sd_internal/runtime.py
img_id generation needs to be part of the for loop for batch generation, otherwise only the latest file of parallel renders will be saved.
> fixed img_id for parallel renders

- ui/media/js/main.js
Small improvement that should help with
Unexpected server task state: completed
Endpoint response does not contains a response stream url.
If not it will at a minimum increase logging and that should help to at least find the remaining issues.
Note: case 'error' has been validated to log properly now by making the backend crash using 'raise Exception()' in the render thread.
> Improved render response checks

- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
Issue #392 
Change curl settings to retry up to 20 times to continue a download, resuming where the previous attempt failed, sleep for 5s between retries (so that the 20 retries don't get consumed too quickly).
> Retry downloads on flaky internet connections

- ui/sd_internal/runtime.py
`Show only the corrected image` is now fixed. I missed that little detail... We were both using `img_data`.
Can't have two vars with the same name...
> Fix TypeError: string indices must be integers

- ui/index.html
- ui/media/css/auto-save.css
- ui/media/css/main.css
- ui/media/css/modifier-thumbnails.css
- ui/media/js/auto-save.js
- ui/media/js/image-modifiers.js
- ui/media/js/main.js
- ui/media/js/parameters.js
Changes
- updated the "popup" system to be more generic and improved its behavior a bit
- moved the system settings to a dialog box
- implemented the system settings as "parameters"
About the new "Parameters"
- I didn't call them settings because we already have "settings" meaning something else (auto-save stuff that includes "Image Settings")
- parameters is maybe a weird name and I'm definitely open to change it or however you want
- I created a new file for them called "parameters.js"
- we could do a lot more with the system like support auto-hide/disable of other parameters etc, but I kept it pretty simple for now
- I defined the system settings parameters in JS but we should be able to define other parameters as json for plugins etc. One advantage of doing it in JS is we can get some …
> Moved System Settings & Reworked into "Parameters"

- scripts/start.sh
changes to the directory containing `start.sh` prior to activating the conda environment
this allows you to run the program without first changing to the correct directory, eg: `$ ~/bin/stable-diffusion-ui/start.sh`
> fix: change to the correct working directory

- ui/server.py
If the CUDA_VISIBLE_DEVICES is already set in config.*, we should copy it over when writing a new config.*, e.g. when switching to beta.
> Copy CUDA_VISIBLE_DEVICES to config.*, it it has been set

- ui/media/css/main.css
No longer scrolls horizontally on small screens / mobile devices, making it much cleaner to use.
> Improve UI on mobile devices

- ui/media/js/main.js
Don't reset reqBody, only replace using req as we use a new task object created from UI inputs.
Fix plugins needing to specify many params or they would be missing in the render request.
> Fix plugins needing to specify many params or they would be missing in the render request.

- ui/sd_internal/runtime.py
Session IDs can be generated by the user, so they should be sanitized to ensure that they don't include problematic characters, e.g. \ or /
> Sanitize session id's before using them as path components

- build.sh
- scripts/Start Stable Diffusion UI.cmd
- scripts/bootstrap.bat
- scripts/bootstrap.sh
- scripts/functions.sh
- scripts/on_env_start.sh
- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
- scripts/start.sh
- ui/sd_internal/runtime.py
- add env variables SD_UI_BIND_IP and SD_UI_BIND_PORT to configure uvicorn
- Add error handling in bootstrap.sh
- check whether the micromamba download was successful. Abort if it wasn't.
- Return "1" in case of errors
- In start.sh, abort if bootstrap.sh was not successful.
- Add an auxilliary file `functions.sh` with a `fail` function, reducing code duplication (#DRY)
- In start.sh, abort execution if git and conda don't work after running bootstrap.sh
- Add tips for common error sources (missing bzip2, missing libsm6 packages)
- cd to the script location on start of 'Start Stable Diffusion UI.cmd' like in start.sh
- Bail out when downloading micromamba fails
https://discord.com/channels/1014774730907209781/1038438436081782784/1038438436081782784
Handling this issue took some turns. …
> Improve error handling

- ui/server.py
Copy over SD_UI_BIND_PORT and SD_UI_BIND_IP variables when rewriting config.sh and config.bat.
See #445 for usage of these vars.
This PR is not part of #445 because the config file handling has been rewritten a lot in beta.
> Protect SD_UI_BIND_PORT and SD_UI_BIND_IP in config files

- ui/media/css/main.css
This fix keeps the settings popup at the same visible position upon scrolling.
> Fix modifier and system settings popup position

- ui/media/js/main.js
When closing the window, a warning is shown if there are any render results.
> Add event listener beforeunload

- scripts/bootstrap.bat
According to this analysis: https://discord.com/channels/1014774730907209781/1040225028828057620/1040324719074889779 the USERPROFILE variable must not contain unicode characters as well. Only setting APPDATA is not sufficient.
> set USERPROFILE to local profile (fixes #468)

- ui/media/css/main.css
- ui/media/js/dnd.js
Adds a paste button next to the copy to clipboard button on top of the image settings.
The button accepts either JSON content or autosave sidecar text file content - the same
content that drag and drop accepts as input.
> Add paste button next to copy button

- ui/media/js/main.js
System info crashes the UI if the render device is not a GPU.
CPU info doesn't contain mem_free => toFixed fails => exception raised => catch() sets server state to offline.
> 🔥Fix system info for CPU mode

- ui/media/js/main.js
By default, healthCheck() is run every 5s. On background tabs, this may get extended. My tests have shown pings every 60s. The ping was older than 10s, so the condition in line 490 evaluates to `false` and the client tries to access the stream before the server is ready. By increasing the validity this can be avoided - at least until the browser runs the healthcheck even less often.
See https://discord.com/channels/1014774730907209781/1041811939380178964/1041812021018120262 for the analysis.
> Incr. Server State Validtiy to 90s

- ui/media/js/main.js
- ui/sd_internal/device_manager.py
- ui/sd_internal/task_manager.py
- ui/server.py
Changed update_render_threads to use SetAppConfigRequest to set which devices are active.
Keep ImageRequest.render_device for affinity only. (Send a task to an already active device.)
> Changed update_render_threads to use SetAppConfigRequest.

- CHANGES.md
- CONTRIBUTING.md
Release notes are important to inform users about added functionality. A change history will make it easier for the release coordinator to compile release notes, instead of having to go through all the commits (several hundred for the last release).
> Add Change history

- ui/index.html
- ui/media/css/main.css
Use a textarea instead of an input field for the negative prompt. Negative prompts can become quite long and editing them in a single line is difficult.
> Textarea for negative prompts

- scripts/on_sd_start.bat
Fixes GFPGANer errors when the env has been moved.
> Rewrite easy_install.pth on each start

- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
For some users who have git preinstalled, `git apply` fails due to whitespace errors.
Aracon found that applying `--whitespace=fix` to the `git apply` invocation fixes the problem.
https://discord.com/channels/1014774730907209781/1036679816713359471/1037025435491516548
ryz confirmed further down in the same thread that `--reject` wasn't needed for him to make it work, and this explanation from the "git apply" manpage suggests that we shouldn't include `--reject`:
> For atomicity, git apply by default fails the whole patch and does not touch the working tree when some 
> of the hunks do not apply. This option makes it apply the parts of the patch that are applicable, and leave 
> the rejected hunks in corresponding *.rej files.
After having a look at …
> Add --whitespace=fix to git apply

- scripts/on_sd_start.bat
`conda activate` fails if %TMP% or %TEMP% contains spaces. So instead of setting the temp variables in the installer steps, we need to set it at the beginning of the script. 
Would this break anything? 
https://discord.com/channels/1014774730907209781/1042190192049668106/1042190192049668106
> Handle %TMP% and %TEMP%

- ui/media/js/image-modifiers.js
Fix for duplicate image modifiers when restoring a task in which several custom modifier cards share the same tag.
> Fix duplicate custom modifiers restoration

- ui/media/js/image-modifiers.js
Fixing activation state for custom modifier cards sharing the same tag where only one of the cards gets (de)activated.
> Fix duplicate custom modifiers activation states

- ui/media/css/main.css
When there are too many tasks and the top of the list is not visible, there is no visual feedback that a task has been successfully added to the queue.
Adding a subtle visual feedback on buttons upon click to reflect that the mouse event was taken into account.
> Visual feedback on button click

- ui/media/js/image-modifiers.js
As per Discord conversation, this PR fixed the image modifiers behavior when a modifier appears more than once (due to custom modifiers), and also fixes a regression introduced by ((weighted modifiers)).
> Hotfix for repeat image modifiers

- ui/index.html
- ui/media/js/dnd.js
- ui/media/js/main.js
Update the seed *before* starting the processing, so interrupting the processing retains the seed being used for the batch being currently processed.
The idea behind that is that if I like the gen I'm currently seeing and want to build on top of it, I can create a new task with the same seed without having to wait for the current task to complete.
> Tweak the seed behavior

- ui/sd_internal/runtime.py
Missing changes from https://github.com/cmdr2/stable-diffusion-ui/pull/561
Fix this issue
```
Traceback (most recent call last):
File "/home/madrang/WorkSpace/StableDiffusion/sd-ui/ui/sd_internal/task_manager.py", line 305, in thread_render
task.response = runtime.mk_img(task.request, task.buffer_queue, task.temp_images, step_callback)
File "/home/madrang/WorkSpace/StableDiffusion/sd-ui/ui/sd_internal/runtime.py", line 442, in mk_img
raise e
File "/home/madrang/WorkSpace/StableDiffusion/sd-ui/ui/sd_internal/runtime.py", line 427, in mk_img
return do_mk_img(req, data_queue, task_temp_images, step_callback)
File "/home/madrang/WorkSpace/StableDiffusion/sd-ui/ui/sd_internal/runtime.py", line 590, in do_mk_img
uc = thread_data.model.get_learned_conditioning(batch_size * [req.negative_prompt]) …
```
> Fix for RuntimeError, missing lines.

- ui/media/js/image-editor.js
With a pen, tipping on a browser page, waiting a short moment, and then moving the pen scrolls the page. Call event.preventDefault() to disable this default behaviour for events in the canvas area.
https://discord.com/channels/1014774730907209781/1021695193499582494/1047965838482874438
> Fix weird scrolling when using a pen

- ui/media/js/image-modifiers.js
Artist modifiers, with the exception of Artstation (the first one), don't have the outline when selected. All the other modifiers, above or below, seem to work as intended
https://discord.com/channels/1014774730907209781/1014774732018683927/1048343258775949322
> Fx: Highlight artist modifiers when clicked

- ui/media/js/main.js
If you have an image selected (img2img) then clicking Upscale on another unrelated image, the image for img2img is used and you get something very unexpected.
> Fix upscaling when a source image is set

- README.md
Old link was broken. Apparently the "develop" branch was deleted.
> Fix download pictures

- ui/media/js/main.js
There is an issue on the beta where if you use pipe ( | ) in the prompt to make a prompt matrix, the optional prompts are only applied when the last prompt in the matrix is used.
cmdr2 - Adding JeLuf's description for the commit message:
This addresses this bug https://discord.com/channels/1014774730907209781/1021695193499582494/1049121128158859285
Optional prompts == modifiers.
Prompt a|b|c
Modifiers x,y
Jobs generated:
a
a,b
a,b,c,x,y
a,c,x,y
The modifiers get appended to the prompt first, then the | symbols are evaluated.
Patrice's PR changes the order, so that the modifiers x,y are always appended:
a,x,y
a,b,x,y
a,c,x,y
a,b,c,x,y
> Fix tags not being properly applied to prompt matrix

- ui/plugins/ui/Autoscroll.plugin.js
After thinking about it, the auto-save toggle is meant for the *Editor* fields listed behind the Configure button. The auto-scroll toggle is not part of the Editor, and is more akin to a system setting, although it's placed in the main UI for convenience reasons related to its nature. As such, and especially considering it's a plugin, I lean towards decoupling auto-scroll from the auto-save settings, and just storing it independently.
> Fix auto-scroll setting management

- ui/media/js/engine.js
Start the countdown to IDLE_COOLDOWN before idleEventPromise is completed (pause removed)
Faster resuming of tasks when removing pause.
> Reduce delay when getting out of idle/pause

- ui/media/css/image-editor.css
- ui/media/js/image-editor.js
Fix issue where portrait images were scaled down that shouldn't have been.
https://discord.com/channels/1014774730907209781/1021695193499582494/1053160065747669022
Add redo/undo-buttons
> Fix img resize issues, add redo/undo buttons

- ui/media/css/main.css
- ui/media/js/main.js
Use a CSS only mouse hover for the initimg in the task bar instead of my previous Javascript based solution (thanks [AssassinJN](https://discord.com/channels/1014774730907209781/1021695193499582494/1053313186234912768))
Add a "Use as Input" button to the initimg hover. Useful for inpainting images which would otherwise be lost.
> CSS only initimg hover, 'use as input' button

- ui/server.py
When `socket.gethostbyname_ex(socket.gethostname())` fails, the exception causes the entire `/get/system_info` call to fail. Due to this, the UI will not learn about the GPU and thus only CPU rendering will be allowed.
https://discord.com/channels/1014774730907209781/1053805801153773680/1054155074127015956
> Return empty list if hostname lookup fails

- ui/media/js/main.js
Allows empty prompts as long as there are image modifiers. This allows the user to craft prompts just by using image modifiers if they so wish.
> Allow empty prompts (image modifiers only)

- ui/index.html
- ui/media/js/engine.js
- ui/media/js/main.js
This is a temporary workaround, until we figure out a better solution.
> Speed up image creation, by removing a delay (regression) of 4-5 seconds between clicking Make Image and calling the server

- ui/index.html
Using a guidance scale of 1.0 will cause an exception in the renderer and return a very confusing error message. https://discord.com/channels/1014774730907209781/1028195513377509376
> Avoid guidance scale "1.0"

- ui/media/js/dnd.js
Fixing the copy settings to clipboard feature. Regression was caused by the processing of the legacy turbo field, which I understand to now be obsolete.
> Fix copy image settings to clipboard

- ui/media/js/image-modifiers.js
Adding events to allow plugins to listen for image modifiers loaded and refreshed events respectively.
> Adding image modifiers events

- ui/easydiffusion/renderer.py
When eye correction, upscaling, and only show filtered image are ALL disabled, the UI still generates two of the same image, and increments the second's seed by 1 (although it's the same image). It doesn't perform an additional process, but the item is shown twice.
> Fix for duplicate images

- ui/media/js/dnd.js
Restore the original prompt if provided... including if it's empty now that empty prompts are allowed if there are modifiers. As shown in the below picture, I created a modifier-only prompt, but upon restoring the task the prompt got copied back in the prompt field, which will cause a duplication of strings in the next task (prompt + image modifiers are the same and will be concatenated).
> Restore the original prompt if provided

- ui/media/css/main.css
If the source image has a high enough resolution it won't fit on the screen when hovering over it. This simple fix limits the max size so the user always has a chance to see the full image.
> Limit the size of zoomed-in source images

- ui/media/js/dnd.js
- ui/media/js/image-modifiers.js
- ui/media/js/main.js
Inactive image modifiers (right click on image tag) are not properly restored by Use Settings and Copy/Paste settings. This PR fixes that.
> Proper restoration of inactive image modifiers

- ui/easydiffusion/device_manager.py
Show the warning that GPUs with <3GB aren't supported only once instead of every 5s
Fixes https://discord.com/channels/1014774730907209781/1059869326313799700
> Prevent flooding the log with warnings for GPU<3GB

- ui/media/css/image-editor.css
Fix for the cut off controls.
Before:
After:
> Fix image editor display

- ui/easydiffusion/model_manager.py
If config.json references an unsupported model, the startup of ED currently fails. Using a `try:` block, the startup can continue if the loading of a model fails.
> Don't crash on unsupported models

- ui/easydiffusion/utils/save_utils.py
Fixes (3) of this list of bugs: https://discord.com/channels/1014774730907209781/1021695193499582494/1060107021870956624
If the autosave files were generated in different seconds, they have non-matching file names in the base64 encoded timestamps. In order to allow automatic processing, these names should match.
> Synchronize .img and .txt autosave file names

- ui/media/js/main.js
I would like to have createTask return the taskEntry.id in order to allow for watchers or callbacks to be able to reference tasks by id more easily.
> return taskEntry.id on createTask

- ui/media/css/main.css
This time to address the height.
Before:
After:
> Another fix for high res images

- ui/media/js/main.js
If 'pause all' is clicked during the last scheduled job, the 'resume all' button gets hidden when the jobs terminates, making it impossible to unpause the engine.
https://discord.com/channels/1014774730907209781/1014780368890630164/1071584183417323602
> Fix 'Pause All' function

- ui/easydiffusion/utils/save_utils.py
it appears that in EasyDiffusion 2.5 the VAE model parameter in metadata files was accidentally removed. I added the missing label so that VAE models are outputted again.
I also removed the `Prompt Strength: 0.8` parameter in metadata files if you're using txt2img, since it's misleading. And I also removed `Hypernetwork Strength: None` when the hypernetwork model is none, since it's unnecessary.
> Restore VAE model in metadata files and remove prompt strength in txt2img generations

- ui/media/js/image-modifiers.js
- ui/plugins/ui/modifiers-toggle.plugin.js
Fix names and toggling for cards starting with "By ", e.g. "By the ocean".
Before: "by " missing from "by the pool", disabled card included in prompt
After: "by the pool" displayed as expected in the card, disabled card not included in the prompt
> Fix card names and toggling

- ui/easydiffusion/app.py
- ui/easydiffusion/server.py
- ui/media/js/parameters.js
Add a config.bat/sh setting `FORCE_SAVE_PATH` that can be used by server admins to restrict auto save to a specific directory. Also useful for users who use different end devices and want to centrally configure the auto save option.
If `FORCE_SAVE_PATH` is set, the auto save options in the UI are disabled.
Fixes #597 
Fixes https://discord.com/channels/1014774730907209781/1052691036981428255
> Enforce an autosave directory

- ui/easydiffusion/model_manager.py
- ui/index.html
- ui/media/js/auto-save.js
- ui/media/js/dnd.js
- ui/media/js/main.js
Add scanning for models and a dropdown to choose different models from.
In some situations, the 1.3 version produces better results, in others, I like the 1.4 version more. I think supporting both makes sense.
This PR might conflict with the changes in #786
Fixes #265
> Support multiple GFPGAN models

- ui/media/js/main.js
- ui/media/js/plugins.js
https://discord.com/channels/1014774730907209781/1014774732018683928/1072787224850092083
Adds a hook that can be used to extend the client side prompt preprocessor, before the prompt is passed on to the tasks.
> Add hook to implement custom prompt preprocessors

- ui/media/css/main.css
Before:
After:
Also opportunistically fixed the indentation of the .simple-tooltip class declaration.
> Fix the tooltip display over image modifier cards

- ui/media/js/main.js
With this change, the number of prompt variants is taken into account when computing the number of images that will be generated. 
`X = getPrompts().length * numOutputsTotalField.value`
Fixes https://discord.com/channels/1014774730907209781/1059237919178637484
https://discord.com/channels/1014774730907209781/1021695193499582494/1063402892058431518
> Fix number on the "Make X images" button

- ui/index.html
- ui/media/js/main.js
Move image containers to their own DIV container to create a clear delineation in the DOM. Purely DOM structural adjustment meant to make a sticky footer possible in the preview pane (for plugins).
HTML generated before:
HTML generated after:
> Group image containers (DOM tweak)

- ui/media/js/dnd.js
In dnd.js, when models are restored in the UI, there is code that strips the path from the model file name. Now that we allow models to be hosted in subfolders, this code break the task restoration (e.g. use settings, D&D, copy/paste) because "/my models/model.ckpt" becomes "model.ckpt", which won't be found.
The fix here essentially looks for the presence of '/models/stable-diffusion/', which we do know would exist in early txt files to decide whether to strip the path.
https://discord.com/channels/1014774730907209781/1014780368890630164/1063911477796417557
> Fix restoration of models with subfolders

- ui/easydiffusion/model_manager.py
- ui/media/js/main.js
With EasyDiffusion 2.5 models stopped being sorted alphabetically, which makes it hard to find a specific model when you have a lot of them. I'm adding back sorting, as well as making the sort case insensitive.
I also changed it so that folders appear on top. For child folders the grandchild folders appear last, to prevent the UI from looking like
* **ChildFolder**
* **ChildFolder/GrandchildFolder**
* Model1
* Model2
when Model2 belongs to ChildFolder and Model1 belongs GrandchildFolder.
I also updated the UI so that folders that only contain more folders will not appear in the select menus.
With sorting:
> Sort models alphabetically

- ui/easydiffusion/utils/save_utils.py
- ui/media/js/main.js
- ui/media/js/parameters.js
*** Please merge https://github.com/easydiffusion/sdkit/pull/9 before merging this one. ***
This is the ED client part of metadata embedding. It adds 'embed' and 'none' options to the metadata setting and makes none the default (if never set before) because (1) it feels weird to create metadata files by default and (2) embedding by default could cause be problematic if users don't realize it's happening.
Also fixes the disabling of the dropdown in the settings when Save images to disk is toggled off.
> Embed metadata

- ui/media/css/main.css
- ui/media/js/main.js
Modify the hide image button to also hide the task when all images are hidden. Added a css class instead of inline style to persist across display changes and allow for future class use for hiding.
> Hide Image buttons hides task

- ui/media/css/image-editor.css
Quick fix  for the inpainter and image editor display when browser window has an horizontal scrollbar.
Before:
After:
> Fix the inpainter and image editor display

- scripts/bootstrap.sh
- scripts/functions.sh
- scripts/on_sd_start.sh
- ui/easydiffusion/app.py
These changes were developed in this [discord conversation](https://discord.com/channels/1014774730907209781/1039581234948476929/1073511002873806908)
- Fix `tar` invocation: Flags need to be provided before filenames
- `find` has no `printf` function on MacOS. Use `stat` instead. Implemented as a `filesize` function
- Fix `sysctl` invocation
- Fix default handling for the network parameters (Fixes #840)
> Changes to make things work on MacOS/x64

- ui/media/js/dnd.js
- ui/media/js/main.js
Task reordering broke due to the introduction of an addition <div> in the preview pane. This PR fixes the task reordering.
https://discord.com/channels/1014774730907209781/1014774732018683926/1073897626837196830
> Fix task reordering

- ui/index.html
- ui/media/js/searchable-models.js
Bug fixes for model search:
- fix navigation issues with arrow keys when filtering models
- fix the issue with arrow keys jumping several entries after model reloading
- disable autocomplete in model search box
- gfpgan: the list with models doesn't appear under the <input> box
- merge models: As long as no models are selected, the <input> box is very short.
- When searching for models by name, the width of the model list shrinks and is smaller than the <input> element.
https://discord.com/channels/1014774730907209781/1014780368890630164/1074468097135747083
> Model search bug fixes

- ui/media/js/dnd.js
In some conditions tasks may be reloaded with an empty file path (e.g. no face correction). This causes the task reloading to throw an exception during the below test because filename is null.
if (filename.includes('/models/stable-diffusion/')) {
...
}
> Fix reloading of tasks with no file path

- scripts/bootstrap.sh
Check whether /proc/cpuinfo exists before checking for AVX support
> No /proc/cpuinfo on MacOS

- ui/plugins/ui/merge.plugin.js
The event listener instantiates two objects every time the user clicks on the Merge tab. This is no longer needed after AssassinJN's CSS fixes from yesterday.
> Cleaning up event listener that's no longer needed

- ui/media/js/searchable-models.js
The new models dropdown sorts a flattened list of models. This can cause issues with subfolders.
Ex: if you have a structure like this:
* foo
* bar
*  baz.safetensors
* aar.safetensors
* car.safetensors
Then the resulting list would currently look like
* **/foo**
* aar
* **/foo/bar**
* baz
* **/foo**
* car
when it would be better as
* **/foo**
* aar
* car
* **/foo/bar**
* baz
Example of current behavior:
New behavior in this PR:
> Fix model folders being split up by child folders

- ui/media/js/main.js
The previous code added an event listener per preview image (if live preview is enabled), so that multiple confirmations were required.
> Only confirm image deletion once

- ui/easydiffusion/app.py
\r\n creates CR CR LF in python, which confuses the Windows batch processor. With only \n, adding the config line for FP32 works as expected:
10:50:43.659 WARNING cuda:0 forcing full precision on this GPU, to avoid green images. GPU detected: NVIDIA GeForce GTX 1060 6GB
https://discord.com/channels/1014774730907209781/1014774732018683926/1076074641669488760
> Remove superfluous CarriageReturn

- scripts/on_sd_start.bat
The size check fails on every installation. The path name of the check wasn't changed when the model was moved to the models directory.
https://discord.com/channels/1014774730907209781/1076486753394905111
> 🔥 Installer: Fix ESRGAN anime model's path

- ui/media/js/dnd.js
Here is a more robust fix for task restoration in dnd.js. Task restoration will fail if the JSON contains "use_face_correction": false, which can happen under some circumstances.
The fix checks if the filename passed to getModelPath is actually a string, which covers both the previous scenario (filename === null) and this new one (filename === false).
https://discord.com/channels/1014774730907209781/1058857864954904607/1076328310138732644
> Fix filename parsing issue

- ui/easydiffusion/types.py
- ui/index.html
- ui/media/js/dnd.js
- ui/media/js/main.js
- ui/media/js/plugins.js
WEBP images are supported by the PIL image library used in sdkit. The format has extremely small file sizes. For example, a 768x760 image that I upscaled 2x to 1536x1536, was
* 189.9 Kb for a 50% quality .webp
* 244.8 Kb for a 50% quality .jpeg
* 637.7 Kb for a 95% quality .webp
* 890.7 Kb for a 95% quality .jpeg
* 3.1 Mb for a .png
All using the same parameters (seed, etc...), just changing the output format. .webp also works for source images in img2img.
I did also test .avif, but PIL throws `ValueError: unknown file extension: .avif`
> Support WEBP image formats

- ui/plugins/ui/modifiers-toggle.plugin.js
The toggling of image modifiers doesn't get properly applied if weights are changed after adding the image modifiers.
Before:
After:
> Fix the toggling of image modifiers

- ui/media/js/image-editor.js
Fixing a visual glitch that becomes visible when a plugin adds borders to the brushes to make them more visible. Visually transparent for the base Easy Diffusion UI.
See this for context; https://discord.com/channels/1014774730907209781/1058857864954904607/1076694770845487155
Before:
After:
> Fix the centering of sharpness brushes

- ui/plugins/ui/Autoscroll.plugin.js
When the first image is generated, the autoscroll triggers before the image is fully displayed by the browser. This causes it to not be positioned properly. The fix is to listen for the "load" event on the IMG element before triggering the scrolling event. Once the image fully loaded and rendered, the browser correctly detects the size of the viewport and renders properly.
Before:
After:
> Fix autoscroll behavior for the first image

- ui/easydiffusion/renderer.py
- ui/easydiffusion/types.py
Make stream_image_progress accept an integer for the rate the progress frames should be generated.
E.g. The default is 5, but now, it can be streamed more or less often.
This change only affects the API; the UI itself is unaffected.
> Make stream_image_progress accept an integer for the rate the progress frames should be generated.

- ui/easydiffusion/model_manager.py
In newer versions of the picklescanner, scanning of .safetensors files creates an error:
21:28:01.067 ERROR MainThread ERROR: parsing pickle in D:\2.35\dev\models\stable-diffusion\dantionrealmix_10.safetensors: at position 1, opcode b'\xce' unknown
To avoid these entries in the logs, skip scanning of safetensors files.
> Don't scan safetensors files

- ui/media/js/main.js
Chrome limits the number of downloads in a batch to about 10 to 12. By delaying the downloads by 200ms, many more downloads are possible. Tested with 200.
https://discord.com/channels/1014774730907209781/1021695193499582494/1077218966205902860
> Download all: Fix to download more than 10 images

- ui/media/css/image-editor.css
Yesterday's PR caused a regression on the active brush display, specifically for Sharpness, which is treated differently from the other brushes in the code. This is the fix.
Before:
After:
> Fix the active selection's display

- ui/media/js/image-modifiers.js
Reloading of image tags with ((weight modifiers)) doesn't reuse the modifier card even if it exists, which means images are not restored either. This change fixes that behavior by ensuring proper matching of the tags with existing modifiers.
Original custom modifier:
Result when reloading weighted image tags:
Before:
After:
> Fix reloading of image tags with weight modifiers

- ui/media/js/image-modifiers.js
No change in existing UI behavior. This change allows image modifier plugins to (optionally) pass the modifier card image as a base64-encoded image.
> Allow modifier images to be passed as base64 images

- ui/media/js/searchable-models.js
In https://github.com/cmdr2/stable-diffusion-ui/pull/894 I accidentally broke the up and down arrow keys switching between models in the dropdown. The issue was that the current logic requires the `<ul>` and `<li>` elements to be flat, but I changed it so the the element structure is a tree
> Fix up/down arrow keys on model selects

- ui/index.html
The preview options button overlaps the image task container when the window width is reduced because of the float:right property of the button. This technique makes the toolbar container grow as needed when it contains a floated element, resulting in cleaner display.
Before:
After:
To confirm, the UI displays as usual when the window is large enough (no change):
> Fix the display of the Preview options button

- ui/media/js/dnd.js
The Inpainting toggle doesn't get restored at the very first attempt.
Repro steps:
1. Create a task with a source image and enable the inpainting toggle.
2. Copy the task to the clipboard
3. Refresh the page (F5)
4. Paste the task from the clipboard
Expected result:
The task gets restored and the toggle is ON.
Actual result:
The task is restored, but the toggle is OFF.
To fix that, we have to restore the toggle's state after loading the source image.
Before (upon initial task restoration):
After (upon initial task restoration):
> Fix the restoration of the inpainting toggle

- ui/media/js/searchable-models.js
Currently one has to click on the model name to select a model. Clicking on the file icon won't work and doesn't do anything. This change fixes that behavior by allowing the user to click on either the model name or the file icon to select a model.
> Select model by clicking on the file icon itself

- ui/media/js/image-modifiers.js
This is purely a DOM update to be able to identify the category a given image modifier is part of - e.g. using .closest(). No UI change.
Sample code using this mechanism in an upcoming plugin:
const category = imageElement.closest('.custom-modifier-category').querySelector('h5').innerText.slice(1)
> DOM tweaking to identify modifier categories

- ui/media/js/image-modifiers.js
The PR https://github.com/cmdr2/stable-diffusion-ui/pull/779/files added code to preserve the full names of truncated image modifiers, but only in the "short image modifiers" code path. This PR fixes that by preserving the full image modifier in the DOM for both regular and truncated modifier names and making sure the right string is used (full string for comparisons, shortened string for display).
> Preserve full names for shortened modifiers

- scripts/on_sd_start.sh
- ui/easydiffusion/device_manager.py
- ui/easydiffusion/task_manager.py
Changes:
* autodetect if MPS is available and if the pytorch version has MPS support.
* change logic from "is the device CPU?" to "is the device not CUDA?".
* set PYTORCH_ENABLE_MPS_FALLBACK=1
Known issues:
* Some samplers (eg DDIM) will fail on MPS unless forced to CPU-only mode
> Add support for MPS when running on Apple silicon

- ui/easydiffusion/device_manager.py
- ui/easydiffusion/task_manager.py
* Reverts the recent 'torch.mps' changes since .mps is only available in torch v2.0, which isn't yet released.
* Includes Hotfitx 984
* Enables 'cpu-only' option when running on Apple silicon.
> Hotfix rollup

- ui/media/js/image-modifiers.js
https://discord.com/channels/1014774730907209781/1014774732018683926/1083821795427233973
Even though the image style gets saved, the setting doesn't get applied when loading the page.
> Fix autosave of modifiers image style

- ui/media/css/image-editor.css
Some users on 4K screens zoom in their browser display, but this causes the editor buttons on the top right to be out of view, and since the editor is not scrollable, they have to zoom out to be able to hit 'save'.
This change fixes that by making the image editor window vertically scrollable if it gets too large. No UI change on smaller screens (e.g. phones).
Before:
After:
> Make the image editor scrollable as needed

- ui/media/js/image-modifiers.js
- ui/media/js/utils.js
- ui/plugins/ui/Modifiers-wheel.plugin.js
Restoration of image tags comprising (((weighted modifiers with truncated nam...))) was broken because the code relied on the shorted modifier (with the ...) and added that to activeTags. On top of that, weights were lost during the restoration process because the code restored the non-weighted image modifiers.
Finally, modifiers passed as weighted enumerations (e.g. (({modifier1, modifier2, modifier3})) are parsed as ((modifier1)), (( modifier2), and (( modifier3)). Notice the extra spaces.
With this fix, reloading tasks and plugins restoring weighted and/or truncated modifiers should work as expected. Also opportunistically fixed the trimming of (({modifier1, modifier2, modifier3})) to properly compute as ((modifier1)), ((modifier2)), and ((modifier3)), i.e. without the extra spaces.
> Fix restoration of weighted tasks with truncated modifiers

- ui/index.html
- ui/media/js/image-modifiers.js
Couple minor usability improvements for the custom image modifiers dialog:
- set the focus to the textbox when opening the dialog
- Escape key closes the dialog and cancels the changes, Ctrl+Enter confirms the changes. No change to the existing UI behavior using the mouse.
> Custom Image Modifiers dialog tweaks

- ui/media/js/main.js
Currently I have to change the focus for the image count to refresh. This change makes it immediate. I've been wondering if 'change' should merely be replaced by 'keyup' but decided against it for accessibility reasons (people who might be using accessibility tools with alternative input methods).
Hope this works for you.
> Refresh the image count as user types

- ui/media/js/image-modifiers.js
Image modifiers may be temporarily hidden by plugins like searchable modifier search box, and when restoring a task (e.g. use settings) the image modifier s copied with the hidden class set, which makes it look like it's missing.
By notifying plugins that the image tags have been refreshed, it allows it to act accordingly (in this case by making sure image tags are visible).
Before:
After:
> Notify plugins when image tags get refreshed

- ui/media/js/main.js
When using the "close image"-X button, the task section gets removed when the last image in the section gets deleted. If the batch has not been completed yet, the remaining images get rendered to a hidden task section. 
This PR prevents the deletion of the task section while it is still processing.
https://discord.com/channels/1014774730907209781/1014774732018683928/1084938951271403550
> Only delete task sections if they are no longer processing

- ui/easydiffusion/server.py
By default, uvicorn uses the 'Content Type' value from 'Computer\HKEY_CLASSES_ROOT\.css' for the Content-Type header in its responses. Some systems have this set to 'application/x-css', an outdated content type used in the early days of CSS. Modern browsers ignore stylesheets that don't have the content-type 'text/css'. This change hardcodes the Content-Type to 'text/css', ignoring the registry.
https://discord.com/channels/1014774730907209781/1084874689769377892
https://discord.com/channels/1014774730907209781/1072804725017280553
> Hardcode CSS content type

- ui/index.html
- ui/media/css/image-modal.css
- ui/media/js/image-modal.js
- ui/media/js/main.js
- ui/media/js/searchable-models.js
This function creates a function to preview an image at full size. It's needed for two plugins I'm working on, a plugin to view rendered images at full size and a image browser.
The image defaults to a size that fits the browser window. There are two buttons, a close button and a button that switches the image to 100% zoom. Additionally, clicking on the backdrop of the modal or pressing Escape will close the modal.
Default zoom:
100% zoom:
To test:
```js
PLUGINS['IMAGE_INFO_BUTTONS'].push({
text: 'View Full Size',
on_click: function(origRequest, image) {
imageModal(image.src)
},
});
```
> Add image modal functionality

- ui/media/js/main.js
Changing the functionality to remove task from dom when all images have been removed. This will save system memory in the browser allowing better performance.
> remove task from dome when removing images

- ui/media/js/main.js
Don't add a copy of the image for each live preview image shown:
> When zooming, only show one copy of the image

- ui/media/js/dnd.js
- ui/media/js/main.js
Also, allow prompt files (one line per prompt) to be dnd'ed
> Load prompt: support JSON and TXT metadata

- ui/media/css/main.css
With the current setting of 1265px, the status and the tab headers overlap:
> Prevent collisions of 'What's new' and the server status

- ui/index.html
Alternatively, `<optgroup>` could be used, but it uses more space, adding a scrollbar to the dropdown:
> Add 'Karras' tag to DPM samplers

- ui/easydiffusion/utils/save_utils.py
The old code had a 1.6% chance of name collisions (AAb/345 and AAB3/45 would generate the same filename) on Linux and 39% on Windows (base64 is case sensitive, Windows isn't). This has already led to data loss: https://discord.com/channels/1014774730907209781/1087720718034280519
This code uses base36 (0-9, A-Z) to avoid case sensitivity issues. To avoid collisions on fast computers or multi GPU computers, the time resolution of the timestamp is changed from seconds to 0.1ms, and the image number isn't added to the timestamp but appended as an extra character. Due to the limitation of the timestamps to 7 characters, the timecode will repeat every 90 days. This shouldn't be an issue since most sessions will not last this long.
Due to the potential data loss and the probably long time that …
> 🔥Hotfix: Avoid name clashes for autosave files

- ui/media/js/main.js
Long file and folder names cause problems on Windows systems.
> Make file names of downloaded files shorter

- ui/media/js/image-editor.js
Repro steps:
From a fresh page, click 'Draw'. Image editor launches.
Draw something and hit 'Save'.
Click 'Draw' again, then click 'Clear'
Expected behavior:
The canvas is cleared.
Actual result:
The previous drawing remains there.
This is happening because during the Save process, the drawing is copied to the background canvas, but the latter is not properly cleared by the Clear button.
> Fix for Clear button in image editor

- ui/media/js/image-modifiers.js
- ui/plugins/ui/Modifiers-wheel.plugin.js
() and [] were actually ignored by the legacy parser, so moving the Ctrl+Wheel shortcut to the InvokeAI syntax of '+' and '-'.
> Moving attention weighting to InvokeAI syntax

- ui/easydiffusion/renderer.py
- ui/easydiffusion/types.py
- ui/easydiffusion/utils/save_utils.py
- ui/index.html
- ui/media/js/auto-save.js
- ui/media/js/engine.js
- ui/media/js/main.js
This flag only applies to WEBPs. It is not the same as 100% quality.
A sample 1536x1536 image (2x upscaled) was:
* 382.3 KB for a 95% webp
* 598.3 KB for a 100% jpeg
* 563.9 KB for a 100% webp
* 2.9 MB for a png
* 2.1 MB for a lossless webp
The 100% quality was achieved by updating the UI to change the max from 95% to 100%.
SDKit PR: https://github.com/easydiffusion/sdkit/pull/23
> Allow saving lossless WEBPs

- ui/media/css/main.css
This will move the status from being vertically centered to being fixed at the top of the page.
1800px current:
1800px with fix:
1280px current:
1280px with fix:
720px current:
720px with fix:
400px current:
400px with fix:
> Fix tab bar when there's many plugin tabs

- ui/media/js/dnd.js
This is to let plugins know that the state of the random seed toggle was programmatically changed by dnd.js. No change for regular UI.
> Fire event when random seed is toggled by dnd.js

- ui/media/js/image-modifiers.js
Fixes a regression introduced by PR 1003 that causes _disabled_ image tags to be restored in an _enabled_ state by the "image modifiers improvements" plugin. No change to the regular UI.
> Fix restoration of disabled image tags

- ui/index.html
- ui/media/css/main.css
- ui/media/js/main.js
Make image deletion, task deletion and automatic task deletion due to deletion of its last image undoable.
The easiest way to implement the undo of the "automatic task deletion due to deletion of its last image" was to use a stack of undoable actions. To limit memory consumption, the undo buffer is limited to 20 entries. 
When elements get evicted from the undo buffer, the related entries in `htmlTaskMap` and `imageRequests` are deleted to reduce memory consumption.
The preview toolbar is kept visible if there are undoable actions.
> Add undo support

- ui/media/css/image-modal.css
Inactive popups have `visibility: hidden`, and because the image modal has a 100vh height it causes a massive empty space at the bottom of the page
> Fix the empty space at the bottom of the page

- CHANGES.md
- CONTRIBUTING.md
- ui/media/css/main.css
- ui/media/js/main.js
Did what @cmdr2 requested and made this not a setting. As a bonus, I added a simple way for plugins to add/modify whatever they want here. A plugin simply adds a key to `taskConfigSetup.pluginTaskConfig`. If this key matches one in the task config, it overwrites it, so you can hide things easily. 
Example: the reason I did any of this in the first place was to hide negative prompt. My plugin is just: `taskConfigSetup.pluginTaskConfig['negative_prompt'] = { label: 'Negative Prompt', visible: () => false }` 
With the value getter, plugins can easily add anything from the task:
`taskConfigSetup.pluginTaskConfig['my_custom_task_config'] = { label: 'Custom', value: (task) => { // get and return value } }`
> reworked how task config is setup

- ui/media/js/image-modal.js
- ui/media/js/main.js
Adds back/forward buttons in the image modal, if there is a previous or next image. The arrow keys also function as the arrow buttons.
> Add back/forward buttons to switch between images in tasks

- ui/media/js/dnd.js
It's all in the title. This properly reset the LoRA selection to None if no lora is provided in the task.
> Reset the LoRA dropdown if not present in the task

- ui/easydiffusion/utils/save_utils.py
- ui/index.html
- ui/media/js/dnd.js
For some reason it's showing up between `Sampler` and `Stable DIffusion Model` instead of `LoRA model`.
> Add LoRA Strength to metadata files

- ui/easydiffusion/server.py
- ui/easydiffusion/utils/save_utils.py
- ui/media/js/parameters.js
- ui/media/js/utils.js
Sequel to https://github.com/cmdr2/stable-diffusion-ui/pull/1020
* Add a listener for `PARAMETERS.push` to add new setting rows when parameters are added
* Support setting parameter values and saving to app.config if `saveInAppConfig`. The `extra=Extra.allow` in `SetAppConfigRequest` is what allows the Python code to retrieve the extra properties
* Support `filename_format` and `folder_format` configs from app.config. The default values will generate the exact same format that it currently does
I added [file-folder-format.plugin.js](https://github.com/ogmaresca/easydiffusion-plugins/blob/main/ui/file-folder-format.plugin.js) to use the new functionality
> Allow loading/saving app.config from plugins and support custom folder/filename formats from app.config

- ui/media/js/dnd.js
When pasting e.g. an image, window.clipboardData).getData('text') returns an empty string, which would delete the prompt. 
https://discord.com/channels/1014774730907209781/1093186485563424838
> Don't paste empty prompts

- ui/media/js/image-modifiers.js
Long custom modifiers in a disabled state (e.g. right-click on the image tag) are properly restored as disabled but are incorrectly shown as "active" in the UI. I somehow missed that in https://github.com/cmdr2/stable-diffusion-ui/pull/1062, so here is the fix for that. This change only applies to plugins that try to restore image modifiers, no change to the regular UI.
> Fix the styling of disabled image modifiers

- ui/media/css/modifier-thumbnails.css
Fixes this: https://discord.com/channels/1014774730907209781/1052771989426814986/1094641806194528266
Repro steps:
Create a very long custom modifier and hover over it with the mouse.
Expected result:
The full modifier text shows up as a tooltip.
Actual result:
No tooltip. Need to hover on a narrow area *below* the modifier for the tooltip to appear.
After checking, this impacts every user, not just people using my plugin, so I think the fix should go in core for everyone to benefit from it.
> Fix the tooltip display for long modifiers

- ui/media/js/dnd.js
Repro steps: create a task with LoRA dropdown set to None, and a second task with a LoRA selected. Then click on Use Settings from the first task.
Expected result: LoRA set to None.
Actual result: LoRA remains unchanged (as selected from second task).
> Properly reset LoRA selection from Use Settings

- ui/easydiffusion/model_manager.py
`is_malicious_file()` already skips the scanning of safetensors files.
This PR adds a similar check to `load_default_models()`, so that no messages like 
```
ERROR: parsing pickle in [...] at position 0, opcode b'\xcd' unknown
```
are logged any more.
https://discord.com/channels/1014774730907209781/1095087265916657695/1095236389290917898
> Don't scan safetensors files in load_default_models()

- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
On Linux, the check is recursively. On Windows, it only checks for files in `models\stable-diffusion`, not in the subdirectories.
If the 1.4 model file _does_ exist, it will still check the size.
> Don't download 1.4 if other models are available

- scripts/on_sd_start.sh
Automatically detects AMD GPUs and installs the ROCm version of PyTorch instead of the cuda one
A later improvement may be to detect the GPU ROCm version and handle GPUs that dont work on upstream ROCm, ether because they're too old and need a special patched version, or too new and need `HSA_OVERRIDE_GFX_VERSION=10.3.0` added, possibly check through `rocminfo`?
For AMD this uses the current latest ROCm version of 5.4.2, and PyTorch 2.0 which is only 2.0 because they felt like it and is basically 1.14 and is entirely backwards compatible, per [their FAQ](https://pytorch.org/get-started/pytorch-2.0/#faqs)
nvidia/cuda is unchanged
----
This was tested and working on a up to date as of this comment Arch Linux system, with ROCm installed according to …
> Automatic AMD GPU detection on Linux

- ui/easydiffusion/model_manager.py
Fixes #882
If the load of the model fails during the initialization, an attempt to render an image using the same model fails because ED doesn't notice that the model has to be loaded. This PR ensures that the model is being reloaded if the initial load fails. If the second load attempt fails as well, the user will get a more helpful error message than 'model not loaded yet'.
> Don't save model_path if initial load fails

- scripts/get_config.py
- scripts/on_env_start.bat
- scripts/on_env_start.sh
- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
- ui/easydiffusion/app.py
Introduces scripts/get_config.py.
> usage: get_config.py [-h] [--default=DEFAULT] key [key ...]
If config.yaml exists, it will use that file. If it doesn't exist, it will look for config.json.
Get the update_branch setting from the config:
`python scripts/get_config.py update_branch`
Get net.listen_port:
`python scripts/get_config.py net listen_port`
Get the net.listen_to_network setting, return False if the setting doesn't exist in the config file:
`python scripts/get_config.py --default=False net listen_to_network`
> Don't write config.bat and config.sh any more

- ui/easydiffusion/app.py
These warnings clog up the logfiles and worry users.
```
G:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\convert_from_ckpt.py:1084: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
with safe_open(checkpoint_path, framework="pt", device="cpu") as f:
G:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using …
```
> Disable "TypedStorage is deprecated" user warnings

- ui/media/css/image-modal.css
- ui/media/js/image-modal.js
When the user zooms in on the image modal, it will allow the user to grab the image to drag it around.
> Allow grabbing the image to scroll zoomed in images

- scripts/check_modules.py
Fixes:
```
File "../scripts/check_modules.py", line 133, in is_amd_on_linux
with open("/proc/bus/pci/devices", "r") as f:
PermissionError: [Errno 13] Permission denied: '/proc/bus/pci/devices'
```
https://discord.com/channels/1014774730907209781/1108542536429093005/1108755274669502586
> Fail gracefully if proc access isn't possible

- README.md
- ui/index.html
- ui/media/js/parameters.js
These new samplers will be hidden when diffusers is disabled.
Also, samplers that aren't implemented in diffusers yet will be disabled when using diffusers.
SDKit PR: https://github.com/easydiffusion/sdkit/pull/35
> Add DDPM and DEIS samplers for diffusers

- ui/media/js/parameters.js
The 'Please restart' text should be part of the note, not the label.
> Network settings - Fix typo.

- ui/media/js/auto-save.js
- ui/media/js/main.js
- ui/media/js/parameters.js
When starting EasyDiffusion for the first time, initialize vram_usage_level based on the amount of VRAM. If cuda:0 has less than 4.5GB, switch to "low".
> Automatically use 'Low' when VRAM<4.5GB

- scripts/get_config.py
https://discord.com/channels/1014774730907209781/1110053226709000222
A corrupted config file prevented the application from starting. With this fix, if the file is no valid yaml/json, proceed using the default value.
> get_config: return default value if conf file is corrupted

- ui/media/js/main.js
- ui/media/js/utils.js
By splitting the confirmation function into two halves, the closure was lost.
https://discord.com/channels/1014774730907209781/1110971052546334791
> Fix confirmation dialog

- ui/media/js/dnd.js
When processing a metadata file, trigger events for changed height/width/prompt fields. Fixes #1290, and also updates the "Make X images" button.
> Remove warning when reusing settings - Fixes #1290

- ui/media/js/dnd.js
Fixes a regression introduced by https://github.com/cmdr2/stable-diffusion-ui/pull/1304 that causes the entire prompt to be restored in the prompt textbox, including the image modifiers, when restoring a task, reusing settings, etc.
Repro steps:
1. Create a task made solely of image modifiers (empty or partial prompt).
2. Start the rendering.
3. Click on Reuse settings.
Expected behavior:
The task is recreated identical to the original, including an empty/partial prompt textbox.
Actual behavior:
The entire prompt built from image modifiers is restored in the prompt textbox (in addition to restoring the image modifiers).
> Fix regression in restore task to UI flow

- ui/plugins/ui/merge.plugin.js
From #1312:
> The "merge models" feature uses opposite ratio compared to what UI says and what the user would expect.
> Fix #1312 - invert model A and B ratio in merge

- ui/easydiffusion/utils/save_utils.py
Fixes
```
/ssd2/easydiffusion/ui/easydiffusion/utils/save_utils.py:222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if task_data.use_upscale is not "latent_upscaler" and "latent_upscaler_steps" in metadata:
```
> Fix SyntaxWarning on startup

- ui/media/js/dnd.js
The word None which many txt metadata files contain as value for the GFPGAN field should not be considered to be a model name. 
If the value is None, disable the checkbox.
Fixes https://discord.com/channels/1014774730907209781/1111703821631102978
Fixes #545
> Fix GFPGAN settings import

- scripts/Developer Console.cmd
- scripts/Start Stable Diffusion UI.cmd
Non-standard COMSPEC settings can cause very odd behaviour on Windows, e.g. permission errors when trying to start `.cmd` files from the Explorer, or issues with nested commands, e.g. in `FOR` loops.
To simplify spotting these issues, I'd like to have the COMSPEC variable displayed in the log output.
The default value is `C:\Windows\System32\cmd.exe`
> Show COMSPEC variable in logs

- ui/index.html
- ui/media/css/main.css
- ui/media/css/modifier-thumbnails.css
- ui/media/js/image-modifiers.js
Fixes and changes to the Image Modifiers and its container. Better flow and more space for clarity and possible future updates regarding modifiers.
Relocated image modifiers closer to the prompt for better flow.
This is how the image modifier container looks like now.
Image style and thumbnail size settings can be found alongside custom modifiers.
- Additionally fixed the document body overflowing when on mobile.
- The Image Modifier UI overhaul shouldn't affect plugins. The plugins that come with Stable Diffusion by default were tested and should work fine without any updates. The overhaul also works with themes, however the light theme can look a bit ugly, didn't have time to fix that, sorry!
- This overhaul focuses on the UI. The JS side of things still need an overhaul, the current …
> Image Modifier UI Overhaul

- ui/index.html
- ui/media/css/main.css
- ui/media/css/modifier-thumbnails.css
- ui/media/js/image-modifiers.js
- ui/plugins/ui/tiled-image-download.plugin.js
- Use `<dialog>` for the Modifier settings (solves z-order issues)
- Harmonize dialog design. Use similar header style for image modifiers, modifier settings and tiled image download dialogs
> Modifier settings dialog improvements

- ui/media/js/image-modifiers.js
This will fix an issue where the box is accidentally closed when attempting to quickly select text in the textarea.
> change event trigger to mousedown

- ui/media/css/main.css
- ui/media/js/main.js
- ui/media/js/parameters.js
Don't show the "Copy" button for the cloudflare hostname if there's no clipboard access (e.g. when accessing ED via LAN)
https://discord.com/channels/1014774730907209781/1122893199304822858
> Don't show copy button without clipboard access

- ui/media/js/utils.js
https://discord.com/channels/1014774730907209781/1021695193499582494/1127653577360425042 
'The.QCC: Embedding window. Switching between at end and at cursor closes the Embedding window'
> Fix dialog closing when interacting with <select> child

- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
Reimplementation of #1284
```yaml
net:
listen_port: 9000
listen_to_network: false
bind_ip: 1.2.3.4
```
Defines an IP to bind to instead of 0.0.0.0
`listen_to_network` must be set to true for bind_ip to have an effect.
> Add Bind IP option

- ui/index.html
This PR enables DPM++ SDE and adds DPM++ 2m SDE.
requires [easydiffusion/sdkit#45](https://github.com/easydiffusion/sdkit/pull/45)
> enable DPM++ SDE, DPM++ 2s a and add DPM++ 2m SDE

- ui/media/css/main.css
This change bypasses the browser's over scroll behavior since it's very easy to scroll and pinch an easydiffusion page and accidentally trigger the browser's "drag to refresh" function which will wipe out any work you may have been doing. The page should now "hard-stop" once you scroll to the top or bottom of the easydiffusion UI.  I switched from the "contain" variable to the "none" variable since contain seemed to have no effect, at least on iOS.
I have done a little play testing on various iOS browsers that work off webkit, and this change seems to function well.
I do not have any Android devices, so it has NOT been tested on android browsers.
Reference:
https://developer.chrome.com/blog/overscroll-behavior/
> Update main.css to fix over scroll behavior on mobile devices

- ui/easydiffusion/utils/save_utils.py
Change text metadata from
```yaml
LoRA model: ['/easydiffusion/models/lora/first.safetensors', '/easydiffusion/models/lora/second.safetensors', '/easydiffusion/models/lora/third.safetensors']
LoRA Strength: [1.05, 1.0, 1.0]
```
to
```yaml
LoRA model: /easydiffusion/models/lora/first.safetensors, /easydiffusion/models/lora/second.safetensors, /easydiffusion/models/lora/third.safetensors
LoRA Strength: 1.05, 1.0, 1.0
```
> Format LoRA model/strength as comma separated string in text metadata

- ui/media/css/auto-save.css
- ui/media/js/parameters.js
Remove the need to reload the page after enabling beta. Make diffusers section directly available after enabling beta.
> Display Test Diffusers checkbox when enabling beta

- ui/media/css/main.css
- ui/media/js/main.js
- Show a warning when a controlnet image has been chosen, but no model
- Highlight the seed, inference steps or controlnet model dropdown if their validation fails.
> Warn when no controlnet model is chosen

- ui/easydiffusion/utils/save_utils.py
- ui/media/js/main.js
This PR does two things:
1. fix embeddings parser: The current parser will find `easynegative`. but it will ignore `(easynegative)0.8`
2. use the new use_embeddings_model varable for metadata instead of the custom one
> fix embedding parser and use standard embedding variable for metadata

- scripts/check_modules.py
We should upgrade to 0.3.3, since it has wheels for all our supported plattforms.
> Remove safetensors hack

- README.md
This makes the readme use [latest download links](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release), avoiding having to manually update it every time.
Kinda a companion to the [pull request I opened for the website](https://github.com/stable-diffusion-ui/stable-diffusion-ui.github.io/pull/5).
(not sure if I should have made this on the beta branch instead)
> Use latest download link to avoid having to manually update readme

- scripts/Start Stable Diffusion UI.cmd
- scripts/start.sh
If the PYTHONHOME variable is set, python will not use the python libraries installed by ED, but those provided by the user. Unsetting PYTHONHOME ensures that the correct libraries are loaded.
https://discord.com/channels/1014774730907209781/1105238156804108398
> Unset PYTHONHOME

- ui/easydiffusion/app.py
- ui/easydiffusion/model_manager.py
- If the models_dir can not be created (permissions, drive doesn't exist), show an error message providing hints what went wrong:
- If the `models_dir` entry in the yaml file is empty, use the default `easydiffusion/models` directory.
https://discord.com/channels/1014774730907209781/1014774732018683926/1147249736072577104
> Error handling for models_dir

- scripts/check_modules.py
This fixes a typo on the URL, a spacing, that is making the module to fail to install on systems with AMD GPUs
> FIX: ROCM download URL

- ui/media/js/image-editor.js
- ui/media/js/main.js
With the limit removed, inpaint can work with image sizes larger than 768 pixels.
> Remove inpaint size limit
