- README.md
> use HTTPS for repo clone instead

- ui/modifiers.json
This is a small set of additional modifiers that have been added. In addition, modifiers were sorted alphabetically within their category (although I did it by hand and I may have missed something).
> Additional modifiers

- ui/index.html
A sibling PR to https://github.com/cmdr2/stable-diffusion-ui/pull/44. When I forked I wasn't really thinking about it, so my first branch was off main, then when I made the PR I realized I wanted to update V2, since that is what I was using, and I think where you probably will continue development. 
Wasn't sure what your merge strategy was so I figured I would make another PR to make it easier to eventually merge down.
> updated filenames for v2

- ui/index.html
Fixing the issue I just created https://github.com/cmdr2/stable-diffusion-ui/issues/43. I love this project and just thought this would be a nice QOL improvement. 
If you would like to see a more individualized approach the the metadata adding with some additional checkbox / toggle UI, I am sure I could add that next.
> updated filename

- ui/modifiers.json
- new artists
- new emotions
- removed the "good" emotion
- one new color
- one new visual style
> Fixed artist names and added more entries

- ui/modifiers.json
Added computer graphics tags (+others) for easier control over shape, material properties and look of the image
> Added computer graphics tags

- CONTRIBUTING.md
Based on the discussion on discord on getting this thing running as a developer.
> Add contributing doc with instructions for dev env

- CONTRIBUTING.md
Need to comment out most of the lines so the `ui` folder symlink doesn't get removed and the `.sh` and `.bat` file changes don't get rolled back on next startup.
> Update CONTRIBUTING.md to instruct commenting out multiple lines

- ui/media/modifier-thumbnails.css
| Before | After |
|--------|-------|
|    ![image](https://user-images.githubusercontent.com/76921756/192064005-9a445a18-8db0-4111-b6d7-d02efb1b423c.png)    |    ![image](https://user-images.githubusercontent.com/76921756/192064034-6dc06455-0b19-409f-a0ec-e931a3434be7.png)   |
> Adjust card label size for very small cards

- README.md
The advanced settings have been renamed to image settings and system settings in the Web UI.
> Advanced settings have been renamed

- ui/media/main.css
- ui/media/main.js
This PR fixes and refactors code related to image items.
1. The download button goes to the wrong place on small screens.
2. Download filename contains the first image's seed if multiple images are made.
> Image item refactor

- ui/media/main.css
- ui/media/main.js
first implementation of resizeInpaintingEditor function.
> Resize canvas following selected aspect ratio

- ui/media/main.css
- ui/media/main.js
> Follow the output aspect ratio in the inpainting editor

- Troubleshooting.md
> Add: ModuleNotFoundError: No module named 'gfpgan'

- ui/sd_internal/runtime.py
Fixed file path bugs introduced by mistake and made img_id sequential based on time for better sorting of renders.
> Fixed file path bugs introduced by mistake and made img_id sequential.

- ui/index.html
- ui/media/auto-save.js
- ui/media/main.css
- ui/media/main.js
Added a way to select themes from the ui. The theme gets saved with the rest of the auto-settings. I added some basic themes, and tried to get some decent examples of how customizable it is. I'm no UX designer but I think some of these look decent. Would definetly be happy to see some additions to the themes by someone who is good at colors.
Also at some point a way to do a "Custom" theme could be cool, where the user can select the colors and watch it change. I gotta go to sleep now though so this is it for me today.
It should be super easy to add new themes, just add them in any included css file as a .theme-example-name and set variables like the ones at the top of main.css. The js code will look for those and auto-populate the dropdown box with them. 
You can select a theme here: …
> Theme Selection

- ui/sd_internal/runtime.py
This fixes the seed output for parallel renders with applied filters
> fix seed for parallel renders with filters applied

- ui/media/js/main.js
fixes the bug, that generates multiple images with upscale and fix face button and parallel renders
> fix multiple images with upscale/fix face button

- scripts/on_sd_start.bat
#392 Resume Downloads
The retry options also don't work on some windows machines: https://discord.com/channels/1014774730907209781/1014774732018683926/1034935751332347922
> Undo curl change

- ui/media/css/main.css
- ui/media/js/main.js
I noticed there was a progressbar element without any logic attached to it, so I implemented a progressbar. CSS animations are cool.
https://user-images.githubusercontent.com/3231343/198419554-1df3da77-c1bd-4a94-a389-03a6b0d4b855.mp4
> Fixed/Implemented Progressbar

- ui/media/js/main.js
Fixed progressbar to be hidden in some edge cases.
> Quick Fix for Progressbar Behavior

- ui/sd_internal/runtime.py
Fix: https://discord.com/channels/1014774730907209781/1021695193499582494/1035321262794358877
and
https://discord.com/channels/1014774730907209781/1035308170664493248
> Apply force_full_precision if was set on device_select.

- ui/index.html
The menu has been renamed, so the welcome text should reflect this.
> Change "Advanced Settings" to "Image settings"

- ui/media/js/main.js
Fixing the parsing of Set and Permute operators in custom tags.
> Fixing the parsing of Set and Permute operators in custom tags

- ui/sd_internal/__init__.py
- ui/sd_internal/runtime.py
- ui/sd_internal/task_manager.py
- ui/server.py
Also fix having to specify cpu when it's the only device present.
use_cpu still works but maps to render_device: 'cpu'
> Implement complete device selection in the backend.

- ui/index.html
- ui/media/css/main.css
- ui/media/js/dnd.js
> Add support for drag&drop for the text files made by the backend

- ui/index.html
- ui/media/css/auto-save.css
- ui/media/css/main.css
- ui/media/js/auto-save.js
- ui/media/js/image-modifiers.js
- ui/media/js/main.js
- ui/media/js/parameters.js
- ui/media/js/utils.js
Changes:
- Changed style of sidebar
- Added tabs
- Tab for main image generation
- Tab for Settings
- Tab for Help & Community
- Updated the style of the navbar to work with tabs
- Lots of small changes
<details>
<summary>
For now the mobile version of the tabs are just icons, no text. We could make this a dropdown menu in the future if we want.
</summary>
</details>
> UI Reorganization & Adding Tabs

- ui/index.html
- ui/media/css/main.css
Add links to the main wiki pages to the Help&Community tab
Mobile view:
Desktop view:
> Add Wiki TOC to the Help&Community tab

- CHANGES.md
- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
- ui/media/js/main.js
- ui/server.py
During getModel(), the server picklescans the model files for potential malicious code in the pickled python objects. If a malicious file is found, the web UI will show a big red error message, the makeImage button will be disabled, and the user must remove the malicious file and reload the UI page.
> Picklescan of model files

- ui/index.html
- ui/media/css/auto-save.css
- ui/media/css/main.css
- ui/media/css/themes.css
- ui/media/js/auto-save.js
- ui/media/js/main.js
- ui/media/js/parameters.js
- ui/media/js/themes.js
- ui/media/js/utils.js
Main Changes:
- added toggle sliders instead of checkboxes for all inputs
- updated settings UI to be similar to Hamunii's design
- added a "Hamunii" theme
- updated the default theme to have dark input backgrounds
- fixed a couple other ui bugs/weirdness like mobile horizontal scrolling etc.
Before:
After:
> Better Toggle Inputs & Updated Settings UI

- ui/media/css/main.css
Make the [save] button flash when clicking it.
> Visual feedback for the save button in the system settings

- ui/media/js/parameters.js
- ui/server.py
- Allow users to choose the uvicorn port
- Allow users to restrict uvicorn to only listen on localhost
> Add network settings to the UI

- CHANGES.md
Sorry, I forgot to commit this change in my previous PR :-(
> CHANGE.md change for IP config

- ui/media/js/main.js
Prevent render jobs to fail with HTTP 422 due to empty fields in the image settings. https://discord.com/channels/1014774730907209781/1043481789706031215/1043481789706031215 https://discord.com/channels/1014774730907209781/1014774732018683927/1042768986871443516
minor change, no CHANGE.md entry
> Prevent empty fields in make image request

- ui/media/js/dnd.js
Should not display button until a fallback is added.
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#browser_compatibility
> Fix pasting in Firefox.

- ui/sd_internal/ddim_callback_sd2.patch
Reverts cmdr2/stable-diffusion-ui#549
> Revert "Update ddim_callback_sd2.patch"

- ui/sd_internal/ddim_callback_sd2.patch
Reverts cmdr2/stable-diffusion-ui#552
> Revert "Patching patch again"

- ui/media/css/main.css
Before the changes
After the changes
> Improved tabs flow on small screens.

- ui/sd_internal/runtime.py
After this changes, all cards can use Fix Faces, but only one at a time will be able to run the filter.
If two try to run the filter at the same time, one will wait until the other finishes before starting.
> Fix the gfpgan fix for multi-gpu

- ui/plugins/ui/Autoscroll.plugin.js
Add an auto-scroll toggle at the top of the image preview pane. When enabled, scrolls to the latest image upon generation.
> Auto-scroll plugin

- ui/media/js/dnd.js
> Fix restoration of model and VAE

- ui/sd_internal/device_manager.py
https://discord.com/channels/1014774730907209781/1047654165347827853/1047654165347827853
> Add Quadro T2000 to force_full_precision list.

- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
- ui/sd_internal/runtime.py
- ui/server.py
Add support for checkpoints in safetensors format: https://github.com/huggingface/safetensors
This format shall be safer than pickle files:
> This repository implements a new simple format for storing tensors safely (as opposed to pickle) and that is still fast (zero-copy).
> Safetensor support (Fixes #599)

- ui/index.html
- ui/media/js/auto-save.js
- ui/media/js/main.js
- ui/media/js/utils.js
- ui/sd_internal/__init__.py
- ui/sd_internal/runtime.py
- ui/sd_internal/task_manager.py
Add a slider to the image options for the JPEG quality.
For PNG images, the slider is hidden.
https://discord.com/channels/1014774730907209781/1014774732018683927/1048876555172065280
> Make JPEG Output quality user controllable

- ui/media/js/engine.js
Yeah, I know... What can I say? I have my OCD too. 👀
> Fixing a typo

- CHANGES.md
- ui/media/css/main.css
- ui/media/js/main.js
Show a small thumbnail of the init image in the task list
Show the full size version of the image on mouse hover
> show initimg in task list

- ui/media/js/main.js
https://discord.com/channels/1014774730907209781/1051580881682313308
> Don't allow to make zero images, make at least one.

- ui/media/js/main.js
Fire an event upon tab change.
> Fire an event upon tab change

- ui/media/js/utils.js
Need an event to know that a collapsible got toggled to be able to resize the panels accordingly. Thanks!
> Fire an event when a collapsible is toggled

- ui/media/css/main.css
- ui/media/js/main.js
Add a handle for drag and drop of the taskEntry:
Fixes the problems reported in https://discord.com/channels/1014774730907209781/1054076068342005882
Copying any of the text in the task entry became impossible, because trying to mark text causes a dragstart event.
> Add drag handle

- ui/media/js/main.js
Change 
> "Processed 1 image in 150.65 seconds"
to
> "Processed 1 Image in 2 minutes 30 seconds" 
to be consistent with the approx. time remaining display while rendering
> Change time display on job

- ui/index.html
- ui/media/css/main.css
- ui/media/js/engine.js
- ui/media/js/main.js
Pause button that will prevent new render tasks from being started. Running tasks will not be interrupted, they can complete.
https://discord.com/channels/1014774730907209781/1014774732018683928/1050977439179874375
https://discord.com/channels/1014774730907209781/1014774732018683928/1051282461419642991
> Pause button

- ui/media/css/main.css
- ui/media/js/main.js
Added some functions in main.js and classes in main.css to allow for styling of the drag and drop sort functionality. I made it classed base so that plugins or themes could overwrite the styling as desired.
> Drag and Drop Styles

- CONTRIBUTING.md
- README.md
- Troubleshooting.md
More edits to the README.md, CONTRIBUTING.md and removed TROUBLESHOOTING.md because it was moved to https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting.
> Changes to Front Docs

- ui/media/js/main.js
- ui/media/js/utils.js
When generating larger batches, I often want to remove the bad results in order to concentrate on the good ones.
> Add "Remove" button to each image's hover menu (Fixes #682)

- ui/media/js/parameters.js
> Add icon to "Process newest jobs first" setting

- ui/index.html
- ui/media/css/main.css
> Fix cut off tooltips display

- ui/plugins/ui/Modifiers-dnd.plugin.js
- ui/plugins/ui/Modifiers-wheel.plugin.js
- ui/plugins/ui/modifiers-toggle.plugin.js
Sorry, forgot these in the first PR.
> Adding image modifier events to core plugins

- ui/media/js/auto-save.js
> Persist the processing order toggle across sessions

- ui/media/js/dnd.js
Fix for https://discord.com/channels/1014774730907209781/1014774732018683928/1055508538228748368
> Fix restoration of hypernetwork dropdown

- ui/media/js/dnd.js
- ui/media/js/main.js
Fix source image, mask, and color profile restoration for use settings, copy/paste, and d&d.
Addresses inpainting issue reported here and then some: https://discord.com/channels/1014774730907209781/1014774732018683928/1055428191021432872
> Img2img settings restoration

- ui/easydiffusion/model_manager.py
- ui/media/js/main.js
http://localhost:9000/get/models output format:
```
{
"active": {
"stable-diffusion": "sd-v1-4",
"vae": "",
"hypernetwork": ""
},
"options": {
"stable-diffusion": [
"arcaneDiffusion_v3",
"v2-1_512-ema-pruned",
"wd-1-4-anime_e1",
[
"~batch_merges",
[
"arcaneDiffusion_v3_comicDiffusion_v2_0.1_SmoothStep",
"arcaneDiffusion_v3_comicDiffusion_v2_0.2_SmoothStep",
"arcaneDiffusion_v3_comicDiffusion_v2_0.3_SmootherStep",
"arcaneDiffusion_v3_comicDiffusion_v2_0.3_SmoothStep",
"hassanBlend_v14_theAllySMix_v10_0.5_SmoothStep"
]
]
],
"vae": [
"vae-ft-mse-840000-ema-pruned"
],
"hypernetwork": [
"invisible_10"
]
}
}
```
> Recursive scanning for models

- ui/media/css/main.css
> Fix display of very large images

- ui/media/js/main.js
Nested models are not properly restored upon page reloading.
> Fix the restoring of the previous nested model

- ui/easydiffusion/device_manager.py
The Nvidia T550 needs full precision to work correctly.
> Add NVIDIA T550 to list of FP GPUs #755

- ui/easydiffusion/device_manager.py
> bugfix for FP GPUs

- ui/easydiffusion/device_manager.py
Fixes https://discord.com/channels/1014774730907209781/1014774732018683926/1064269949339697163
> Add NVIDIA T1200 to the list of FP GPUs

- ui/easydiffusion/server.py
- ui/easydiffusion/types.py
- ui/easydiffusion/utils/save_utils.py
Adds an API endpoint that accepts merge requests.
Adds dot, dash and underscore to the list of allowed characters in filenames.
> Backend side merge API

- ui/easydiffusion/device_manager.py
https://discord.com/channels/1014774730907209781/1068948110304354314
> Add T600 to list of FP only GPUs

- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
https://discord.com/channels/1014774730907209781/1072423234676461619
> Use "python -m pip" instead of "pip"

- ui/easydiffusion/device_manager.py
https://discord.com/channels/1014774730907209781/1057627377120858222/1073039929547964488
> Add T500 to list of full precision cards

- ui/media/js/main.js
expose if the user requested a random seed or used a fixed seed
> add random_seed flag to reqBody

- scripts/Start Stable Diffusion UI.cmd
- scripts/bootstrap.sh
- scripts/start.sh
There are a handful of users every week that try to install from a git checkout, see
https://discord.com/channels/1014774730907209781/1065014040058933319
https://discord.com/channels/1014774730907209781/1064148631516614727
https://discord.com/channels/1014774730907209781/1062636187191361666
> Warn when running installer from git checkout

- ui/easydiffusion/device_manager.py
https://discord.com/channels/1014774730907209781/1073819636329631754
> Add k40m to list of FP32 cards

- scripts/on_env_start.sh
- Copy functions.sh from git repo as well. Otherwise it will use the `main` functions.sh together with the `beta` on_sd_start.sh
- Remove duplicate 'Press any key' call. There is a "Press any key" line in both on_env_start.sh and on_sd_start.sh. Also, use `exec` to replace the bash process.
https://discord.com/channels/1014774730907209781/1074411964966653992
> Linux Installer fixes

- ui/index.html
- ui/plugins/ui/merge.plugin.js
As per our recent chat.
https://discord.com/channels/1014774730907209781/1014780368890630164/1074627221534294068
> Fix autocomplete in GFPGAN and Merge

- scripts/on_env_start.sh
https://discord.com/channels/1014774730907209781/1014780368890630164/1074683519772655686
> Fix typo in `cp functions.sh`

- scripts/on_env_start.bat
- scripts/on_env_start.sh
- scripts/on_sd_start.bat
- scripts/on_sd_start.sh
`functions.sh` needs to be updated in `on_sd_start.sh` as well, since the update of `on_env_start.sh` happens too late to put the new `functions.sh` file in place.  https://discord.com/channels/1014774730907209781/1021695193499582494/1074959802259755108
Also, replaced all _Stable Diffusion UI_ messages by _Easy Diffusion_ messages, also on Windows.
> Fix functions.sh upgrade, change messages to Easy Diffusion

- ui/media/css/searchable-models.css
- ui/media/js/searchable-models.js
As per https://discord.com/channels/1014774730907209781/1021695193499582494/1075068193753804831
The only limitation is that we cannot visually gray out the chevron itself because the corresponding font-awesome icon is a Pro icon (https://fontawesome.com/icons/angle-down?s=duotone&f=classic).
> Add support for disabled state to model dropdown

- ui/media/js/searchable-models.js
Fix for my previous PR. Apologies for this silly copy/paste mistake.
https://discord.com/channels/1014774730907209781/1014780368890630164/1075782233970970704
Before:
After:
> Fix the chevron enabled state upon refresh

- ui/media/js/main.js
https://discord.com/channels/1014774730907209781/1021695193499582494/1076685193362030602
> Download all: Fix file name suffix

- ui/media/js/searchable-models.js
> Select but don't empty the search box upon selection

- ui/media/js/parameters.js
Little bugfix to show save toggle as enabled and to be able to select metadata output.
> Bugfix for enforce autosave

- scripts/on_sd_start.bat
Prevent the 'SSL module is not available' error message
https://discord.com/channels/1014774730907209781/1076822300214694008
> Copy SSL DLLs

- ui/media/js/main.js
Just a little fix for the thumbnail slider to support live change of image size while changing the slider value.
> fix for thumbnail slider to support seamless resize

- ui/media/js/searchable-models.js
Is it okay for you if I comment this in Beta?
> Cleanup logging

- scripts/bootstrap.sh
https://discord.com/channels/1014774730907209781/1064237509913084087/1064237509913084087
> Remove AVX check

- ui/media/css/main.css
As per https://discord.com/channels/1014774730907209781/1014780368890630164/1080772220760109066.
> Fix the display of the preview scale slider

- ui/index.html
- ui/media/css/main.css
- ui/media/css/themes.css
- ui/media/js/main.js
Show a warning if the user chooses width & height < 512px
> Warn users about small image dimensions

- ui/media/css/main.css
- ui/media/js/main.js
Right now the plugins for image info buttons can easily overflow, especially if you shrink image sizes. But there are some plugins that don't need to have so many lines, for example the OutpaintIt plugin needs 5 buttons when it could instead be 5 buttons on one line.
This makes two changes:
1. Add support for a `elem` function. This function has one parameter with the schema `{ createButton: () -> HTMLElement, req: Object, img: HTMLImgElement }`. `createButton` here is a function that takes a value from `IMAGE_INFO_BUTTONS`, while `req` and `img` are the same values from the `on_click` function.
2. The `text` field can now be a function that returns an `HTMLElement`, to support things like icons.
I didn't do anything about styling, so when using `elem` any text not created from the …
> Allow creating custom HTML elements for image info button plugins

- ui/media/js/dnd.js
Adds support for LoRA models to dnd.js (task restoration, use settings, etc.).
> Add support for LoRA models to dnd.js

- ui/media/js/image-editor.js
https://discord.com/channels/1014774730907209781/1021695193499582494/1090733238034645082
> Fix key presses in the image editor

- ui/media/js/main.js
Increase random seed range from 10,000,000 to 4,294,967,295 like Automatic1111.
> Increase the random seed range

- ui/media/css/fonts.css
I don't know why it breaks only for a few users, but this patch seems to fix the issue. https://discord.com/channels/1014774730907209781/1081867905907572746 https://discord.com/channels/1014774730907209781/1093215237307637901/1093223612615491604
> fix font definition for some users

- ui/easydiffusion/utils/save_utils.py
https://discord.com/channels/1014774730907209781/1093703857516843019
> fix filename_format for 'show only upscaled'==false

- ui/easydiffusion/model_manager.py
Provide a hint to users what ED is currently using.  Use case: User has built an infinite loop using symlinks, ED model scan will never finish.
https://discord.com/channels/1014774730907209781/1097764777553580092
> Add "Start scanning..." to getModels()

- scripts/on_sd_start.bat
Set HF_HOME, so that the models don't get downloaded again.
> Stop messing with %USERPROFILE%

- ui/media/js/utils.js
- ui/plugins/ui/merge.plugin.js
- ui/plugins/ui/release-notes.plugin.js
Also update the What's New and Merge tabs to use the new function. This means that the app will not reach out to Github for the changelog until the user clicks on the What's New tab
> Add a utility function to create tabs with lazy loading functionality

- ui/media/js/parameters.js
https://discord.com/channels/1014774730907209781/1101629831839494344
> "Please restart" note for network settings

- ui/media/js/main.js
Don't fail when the Hypernetwork Strength text input field is empty
https://discord.com/channels/1014774730907209781/1102237942526791693/1102246254932660385
> Default value for hypernetworkStrength

- ui/media/js/image-modifiers.js
Fix for this bug report: https://discord.com/channels/1014774730907209781/1052771989426814986/1103693919495131230
> Fix restoration of inactive image modifiers

- ui/easydiffusion/device_manager.py
https://discord.com/channels/1014774730907209781/1014774732018683926/1107677076233912340
> Add GTX1630 to list of FP32 GPUs

- ui/plugins/ui/Autoscroll.plugin.js
Error report: https://discord.com/channels/1014774730907209781/1085803885500825600/1108150298289115187
> Fix error when removing image

- ui/easydiffusion/renderer.py
- ui/easydiffusion/utils/save_utils.py
- ui/media/js/dnd.js
Also, force the properties to be in a consistent order so that, for example, LoRA strength will always be the line below LoRA model. I've rearranged the properties so that they are saved in the same order that the properties are laid out in the UI
> Add Clip Skip to metadata files

- ui/easydiffusion/types.py
- ui/index.html
- ui/media/js/auto-save.js
- ui/media/js/dnd.js
- ui/media/js/engine.js
- ui/media/js/main.js
> Add seamless tiling support

- ui/easydiffusion/utils/save_utils.py
- ui/media/js/auto-save.js
- ui/media/js/dnd.js
Also fix txt metadata labels when also embedding metadata
> Add tiling and latent upscaler steps to metadata

- ui/plugins/ui/tiled-image-download.plugin.js
Downloader for tiled images. Creates larger images by tiling them with the image generated by ED. "Open in new tab" option for quick inspection.
> Tiled image download plugin

- ui/index.html
- ui/media/js/main.js
- ui/media/js/utils.js
Some LoRAs like https://civitai.com/models/58390/detail-tweaker-lora-lora and https://civitai.com/models/62700/ivorygoldai can get good results with strengths outside of the [0, 1] range
> Allow LoRA strengths between -2 and 2

- scripts/check_modules.py
- ui/easydiffusion/server.py
- ui/index.html
- ui/media/css/auto-save.css
- ui/media/css/main.css
- ui/media/js/engine.js
- ui/media/js/main.js
- ui/media/js/parameters.js
Shares the Easy Diffusion instance via https://try.cloudflare.com/
Since the list of settings has become quite long, I've put the sharing related settings into their own section.
> Share ED via Cloudflare's ArgoTunnel

- scripts/developer_console.sh
Make behaviour consistent with on_env_start.sh
> Set PYTHONNOUSERSITE=y in dev console

- ui/media/js/parameters.js
Fixes:
https://discord.com/channels/1014774730907209781/1120045444039463052
https://discord.com/channels/1014774730907209781/1118837091850276874
> Fix saving of network settings

- scripts/Developer Console.cmd
Fix https://discord.com/channels/1014774730907209781/1121190941206777977/1121210065907621918
> Run dev console in ED directory

- ui/media/css/main.css
- ui/media/css/themes.css
> move (some) hardcoded colors to variables

- ui/index.html
- ui/media/css/main.css
- ui/media/css/themes.css
- ui/media/js/image-modifiers.js
- ui/media/js/main.js
- ui/media/js/utils.js
- ui/plugins/ui/tiled-image-download.plugin.js
Style the download dialog like the modifiers setting
Make dialogs draggable. Click on the dialog's window title bar to move the dialog
> Download dialog redesign, moveable dialogs, code cleanup

- ui/media/css/main.css
- ui/media/css/themes.css
https://discord.com/channels/1014774730907209781/1014780368890630164/1124408388240015461
> Rollback --backdrop-color var, to fix themes dialog

- scripts/on_sd_start.bat
Fixes https://discord.com/channels/1014774730907209781/1014774732018683926/1128441748637626499
> Fix uvicorn issues after reloacting install dir

- ui/media/js/main.js
Warning until https://github.com/huggingface/diffusers/issues/3922 is fixed.
> Warn about low vram profile when using embeddings

- ui/easydiffusion/utils/save_utils.py
The values will be comma separated
> Add embeddings to metadata

- ui/media/js/main.js
- Using an Embedding on 'Low'
- Using LORAs and models with mismatching versions
> Help texts for common errors

- ui/index.html
- ui/media/css/main.css
- ui/media/js/image-modifiers.js
- ui/media/js/main.js
- ui/media/js/utils.js
Harmonization with the modifiers dialog
> Collapsibles for the embeddings dialog

- ui/index.html
- ui/media/css/main.css
- ui/media/js/main.js
- ui/media/js/parameters.js
- ui/plugins/ui/image-editor-improvements.plugin.js
> Restore width/height dropdown

- ui/easydiffusion/utils/save_utils.py
`dnd.js` will need to be updated separately
> Add ControlNet model and filter to metadata

- ui/media/js/main.js
> Error messages for SDXL embeddings and SDXL yaml files

- ui/media/css/main.css
- ui/media/js/main.js
> Controlnet thumb in taskConfig

- ui/media/js/main.js
> Hide empty folders in embeddings search results

- ui/easydiffusion/server.py
- ui/easydiffusion/utils/__init__.py
To be used from javascript to collect metadata from civitai 
https://civitai.com/api/v1/model-versions/by-hash/0A35347528
> API to get SHA256 of a model file

- ui/index.html
- ui/media/css/main.css
- ui/media/js/main.js
- Don't show "Use as thumbnail" if no embeddings were used in the prompt
- Fix layout issue on small screens
- use req.use_embeddings_model instead of parsing the prompt
- Add button to upload a thumb" ../../index.html ../css/main.css main.js
> Improvements/Fixes for embeddings UI

- ui/index.html
> type=number for "number of images" fields

- ui/easydiffusion/model_manager.py
https://discord.com/channels/1014774730907209781/1014774732018683926/1144179143873929288
There seem to be ".pt" LORA files in the wild.
> Add ".pt" to the Lora extensions

- ui/media/js/main.js
- ui/plugins/ui/lora-prompt-parser.plugin.js
https://discord.com/channels/1014774730907209781/1021695193499582494/1144298414725668864
> Support lora models in subfolders when scanning the <lora> tag

- ui/index.html
Use [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) hints for mobile browsers.
On my phone, the "decimal" keyboard gets used for all of the input modes, so I'm not sure whether this will fix Putan's issue.
https://discord.com/channels/1014774730907209781/1145441618971873310
> inputmode=numeric/decimal for <input> fields

- scripts/check_modules.py
This reverts commit 3a5e0cb2d245a4651521badabd3019293a89c6ca.
> Revert "Continue using uvicorn directly on windows"

- scripts/check_modules.py
- Check whether the user has access to the Kernel Fusion Driver `/dev/kfd`, which is a component of the AMD ROCm stack.
- removed unused environment variable
> AMD/Linux: Warn about file permissions

- scripts/check_modules.py
During the first installation, rich is not yet installed.
Fixes #1582 
https://discord.com/channels/1014774730907209781/1151465739228827668
> 🔥 FIX Linux installer: Don't use rich

- ui/easydiffusion/server.py
- ui/easydiffusion/utils/__init__.py
- ui/media/js/main.js
- ui/plugins/ui/merge.plugin.js
> Lora Manager

- ui/easydiffusion/bucket_manager.py
- ui/plugins/ui/merge.plugin.js
- avoid console errors in python and JS code
- suppress localhost:9000/null links
> Loramanager fixes

- ui/index.html
- ui/media/css/main.css
https://discord.com/channels/1014774730907209781/1014774732018683928/1155386128396984341
> Fix 'Swap width&height' tooltip

- ui/index.html
Quick fix to navigate to the correct Sampler wiki page. 
Closing #1647
> Fix Sampler learn more link
